In [1]:
print('jupyter working')

jupyter working

In [2]:
import pandas as pd

df = pd.read_csv("../data/loan_dataset.csv")
df.head()

   age     income  credit_score  dependents  home_owner  loan_approved
0   54  100000.00           334           0           1              1
1   67   85233.42           593           2           1              1
2   29   16737.15           502           0           0              1
3   42   69332.50           367           3           0              0
4   58   28211.14           430           0           1              1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            1000 non-null   int64
 1   income         1000 non-null   float64
 2   credit_score   1000 non-null   int64
 3   dependents     1000 non-null   int64
 4   home_owner     1000 non-null   int64
 5   loan_approved  1000 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 47.0 KB

In [4]:
df.describe()

,age,income,credit_score,dependents,home_owner,loan_approved
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.54400,31943.240590,573.644000,2.027000,0.494000,0.782000
std,13.95345,28058.315386,163.781078,1.422074,0.500214,0.413094
min,20.00000,4000.000000,300.000000,0.000000,0.000000,0.000000
25%,33.00000,11057.325000,423.500000,1.000000,0.000000,1.000000
50%,44.00000,21712.035000,572.000000,2.000000,0.000000,1.000000
75%,57.00000,42369.575000,720.000000,3.000000,1.000000,1.000000
max,69.00000,100000.000000,849.000000,4.000000,1.000000,1.000000

In [5]:
df.isnull().sum()

age              0
income           0
credit_score     0
dependents       0
home_owner       0
loan_approved    0
dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv("data/raw/loan_dataset.csv")
print(df.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/loan_dataset.csv'